src/components/uni-combox/uni-combox.vue

uni-combox组件增加数据类型兼容，传入参数（数组）带纯数字选项时，因没有indexOf而方法产生报错！
1. indexOf查找时toString避免报错
2. 传入数据类型增加Number避免v-model报错
3. 数字||字符串组成的数组其实可正常使用即可

uni-combox组件数据类型兼容问题

---

docs/components/rate.md

纠正了在Rate评分的doc页面默认加载popup的demo

docs: Update rate doc with the correct demo url

---

uni_modules/uni-list/components/uni-list-chat/uni-list-chat.vue

测试vue3下，nvue页面，不能正常显示圆角 ，社区有overflow: hidden;失效相关提问不知是否相关。
暂通过给image添加header--circle解决

nvue下avatarCircle圆角头像无效

---

uni_modules/uni-indexed-list/components/uni-indexed-list/uni-indexed-list.vue

fix uni-indexed-list 点击列表项事件e.itemIndex不正确问题

---

uni_modules/uni-popup/components/uni-popup/uni-popup.vue
uni_modules/uni-transition/components/uni-transition/uni-transition.vue

给 popup 和transition 组件添加了一个 onceRender 属性, 该属性可以指定组件使用 v-show 切换来避免多次渲染在复杂弹出组件下的卡顿问题, 不破坏当前组件的任何功能, 
如果组件内数据不需要频繁更新就可以使用 once-render 来避免重复渲染, 大幅提升复杂场景下的组件性能问题

给pop组件添加 onceRender 属性来避免重新渲染Pop组件导致的页面卡顿问题

---

uni_modules/uni-popup/components/uni-popup/uni-popup.vue

Fix: 更新 popup 组件内遗漏的 once-render 配置, transition 传递此 prop 才能保证 slot 按需渲染

Fix: 更新遗漏的once-render配置, 传递此 prop才能保证slot按需渲染

---

uni_modules/uni-easyinput/components/uni-easyinput/uni-easyinput.vue

Normal in v1.4.15. There was an unsolvable white background when I updated to v1.4.20.

fix(uni-easyinput): background color is hardcode and can't be changed

---

uni_modules/uni-datetime-picker/components/uni-datetime-picker/time-picker.vue

问题：打开日期选择器后，时间空白。再次修改后，时间为当前时间。
https://ext.dcloud.net.cn/plugin?name=uni-datetime-picker

fix: vue3-time-picker modelValue

---

uni_modules/uni-transition/components/uni-transition/createAnimation.js

此文件的行尾标识符混乱，本次commit统一改成LF，请打开Hide whitespace进行review

fix: 修复Vue3+iOS10+QQ小程序平台下动画报错的问题

---

uni_modules/uni-easyinput/components/uni-easyinput/uni-easyinput.vue

原因：modelValue 为空字符串时 "" ，自动变更为 this.value 
导致双向绑定数据变更为 undefined
会导致用户字段丢失
优化：保留空字符串

fix(uni-easyinput)：优化空字符串

---

uni_modules/uni-combox/components/uni-combox/uni-combox.vue

Reason: Now I have to assign an empty string to `v-model` to return all candidates ​​initially. I don't think JavaScript falsy like `null` and `undefined` ​​should be considered filter conditions. Most of the people prefer to use `null` as an initial value instead of `""`.

fix(uni-combox)：add falsy filter handling

---

uni_modules/uni-combox/components/uni-combox/uni-combox.vue

问题：在微信小程序上使用uni-combox组件时发现滚动选项时会将选项框隐藏。
原因：input框在blur时会启动后一个定时器将showSelector置为false，导致选项框隐藏。在滚动选项时恰好触发了blur事件。
解决: 监听scroll-view的scroll事件，将blur的定时器清除。新增一个蒙层，点击蒙层时可收起选项框。

fix(uni-combox): 优化uni-combox组件候选列表滚动时被收起问题

---

uni_modules/uni-combox/components/uni-combox/uni-combox.vue

因样式没有scoped，类名需添加前缀。设置堆叠层级，使得蒙层覆盖页面。

fix(uni-combox):蒙层类名规范化并设置堆叠层级

---

uni_modules/uni-countdown/components/uni-countdown/uni-countdown.vue

git diff有点奇怪，多了很多相同地方的diff，我并未开启格式化工具，我想也许是因为行尾换行符导致的
实际上我只改动了以下代码
```js
zeroPad: {
type: Boolean,
default: true
}
```
```js
day = (day < 10 && this.zeroPad) ? `0${day}` : day
hour = (hour < 10 && this.zeroPad) ? `0${hour}` : hour
minute = (minute < 10 && this.zeroPad) ? `0${minute}` : minute
second = (second < 10 && this.zeroPad) ? `0${second}` : second
```
这个需求来自社区反馈：
> https://ask.dcloud.net.cn/question/155494

:sparkles:feat: feat(uni-countdown): 新增zeroPad参数-是否补0

---

uni_modules/uni-file-picker/components/uni-file-picker/uni-file-picker.vue

fix #694
这个bug同时会影响（ 前提是手动上传，autoUpload: flase ）
1.上传成功后直接上传或对现有图片再增删再手动上传会错误
2.设置v-model回显，再添加图片，上传异常
另外官网上标明如果要设置回显，v-model最起码要绑定以下三个属性，[链接](https://uniapp.dcloud.net.cn/component/uniui/uni-file-picker.html#value-%E6%A0%BC%E5%BC%8F)
```
"name":"file.txt",
"extname":"txt",
"url":"https://xxxx",
```
这样回显是没问题，如果回显直接点击上传，或再添加几张图片上传，就会有问题，
此时还要绑定以下属性才有效果
```
image: { width, height },
uuid: Date.now(),
status: 'ready',
progress: 0,
fileType: 'image',
cloudPath: `${Date.now()}_${index}.${extname}`
```

fix(uni-file-picker):手动上传删除一个文件后不能再上传的bug

---

uni_modules/uni-nav-bar/components/uni-nav-bar/uni-status-bar.vue

之前的默认高度没加px不生效，而且在mounted中获取高度会导致组件高度有一个变化的过程，在小程序端进入页面时会导致整个页面闪动，非常影响体验
https://user-images.githubusercontent.com/52436248/215699792-4f349070-675b-44a4-a384-8e2bec629e4a.mp4
修改后
https://user-images.githubusercontent.com/52436248/215700375-5f4b24f9-c704-475e-ad2f-0a947e6bc7c8.mp4

fix(uni-status-bar): 修复自定义状态栏高度闪动问题

---

uni_modules/uni-calendar/components/uni-calendar/uni-calendar.vue
uni_modules/uni-calendar/readme.md

1，修复日历头部picker选择年月时未触发monthSwitch事件的BUG（或者是触发change事件？但感觉既然是选择年月，那么触发monthSwitch更合理一些）
2，原先文档缺少正确md标签，无法正常显示表格，新增标签后使其能正常显示

fix(uni-calendar):修复日历头部picker选择年月时未触发monthSwitch事件的BUG及更新文档

---

uni_modules/uni-calendar/components/uni-calendar/uni-calendar.vue

修改了执行顺序，先执行 this.init，再判断是否执行 this.monthSwitch

fix(uni-calendar): 切换到今天时，先触发了monthSwitch，然后设置的日期，导致月份切换的时间是旧日期

---

uni_modules/uni-nav-bar/components/uni-nav-bar/uni-nav-bar.vue

fix(uni-nav-bar): 修复使用自定义导航栏并开启下拉刷新时 onPullDownRefresh 的 loading 元素被导航栏遮挡的问题

---

uni_modules/uni-popup/components/uni-popup/uni-popup.vue

bug复现步骤
1.打开弹窗，触发了 `overflow:hidden`
2.切换页面，由于`keep-alive`的存在，页面没有被销毁，页面无法滚动

bugfix(popup): 修复H5环境下切换页面后overflow:hidden仍然生效的问题

---

uni_modules/uni-popup/components/uni-popup-dialog/uni-popup-dialog.vue

uni-popup 组件增加 showClose 参数判断后，如果取消按钮不展示了，则两个按钮中间的那个线，应该也不要展示了。
修改后该线的样式也随 参数 showClose 一起判断。

fix:增加showClose参数判断后样式判断

---

uni_modules/uni-search-bar/components/uni-search-bar/uni-search-bar.vue

The return value of `@clear` in SearchBar is different from the document. and obtained modelValue is still old value.

fix(uni-search-bar): modelValue is old value when executing clear event

---

uni_modules/uni-table/components/uni-th/filter-dropdown.vue

中国是东八区，`toISOString()` 获取的是0时区时间。也就是说，在0点到8点，`toISOString().split('T')[0]` 取到的时间是前一天的时间。

修复 toISOString() 引发的时区问题（#919重新提交）

---

uni_modules/uni-data-select/components/uni-data-select/uni-data-select.vue

修复 清除按钮不展示问题 及 点击清除图标时值已清除但界面仍显示的 bug
DCloud社区相关提问：https://ask.dcloud.net.cn/question/195178
------
这个问题一共是由1个uni-ui的bug和一个uniapp的内部bug共同引起的
1. 内部组件的bug: 点清除icon其实值已经清除了，但是界面上显示值 (this.current) 忘了更新
解决方案：clearVal函数中清除 this.current
```javascript
clearVal() {
this.emit('')
this.current = '' // 添加此行
if (this.collection) {
this.removeCache()
}
}
```
2. uniapp 内部bug: vue2 误认为两个不同的<view><icon/></view>是一样的，所以其实代码逻辑已经让他显示 x 了，但是界面上响应式认为没变化，就还是之前的icon，目前能做的就是加个 key 明确这两个组件是不同组件
解决方案：给两个<uni-icons>的上层<view>添加不同key属性
```html
<view key="clear-button" v-if="current && clear && !disabled" @click.stop="clearVal">
<uni-icons type="clear" color="#c0c4cc" size="24" />
</view>
<view v-else>
<view key="arrow-button" v-else>
<uni-icons :type="showSelector? 'top' : 'bottom'" size="14" color="#999" />
</view> …
```

fix(uni-data-select): 修复 清除按钮不展示问题 及 点击清除图标时值已清除但界面仍显示的 bug

---

uni_modules/uni-file-picker/components/uni-file-picker/uni-file-picker.vue
uni_modules/uni-file-picker/components/uni-file-picker/upload-image.vue

复现方式：使用本仓库的demo，即可复现
修复后：
修复前：

bugfix(uni-file-picker): 修复支付宝小程序端的默认插槽的样式问题

---

pages/vue/easyinput/easyinput.vue

1. 插槽名称已变更为left和right插槽，示例页面还是使用的prefixIcon/ suffixIcon 插槽，导致示例页面功能未正常使用，提交了修复希望pr能够合并。
现：
pr:

fix(easyinput): 修复easyinput示例页面插槽名称不正确

---

uni_modules/uni-datetime-picker/components/uni-datetime-picker/uni-datetime-picker.vue

fixbug: v-model绑定字符串值类型的时候，在日历面板选中其他日期后，通过改变v-model绑定值重置为默认值，但是日历面板选中状态未能选中默认值。

重置默认值，未能在日历面板展示的默认值未选中状态
